language: php

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - DEPENDENCIES=""
    - php: 5.5
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - php: 5.6
      env:
        - DEPENDENCIES=""
    - php: 5.6
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - php: 7
      env:
        - DEPENDENCIES=""
        - TEST_COVERAGE=true
    - php: 7
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"

before_script:
  - composer self-update
  - composer update --prefer-dist $DEPENDENCIES

script:
  - php ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run
  - ./vendor/bin/docheader check examples/ src/ tests/

after_success:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/coveralls -v; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/61c75218816eebde4486
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
