name: integration
on: [push]

jobs:
  code-standard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
      - name: Install dependencies
        run: composer update --prefer-dist
      - name: Building
        run: ./vendor/bin/php-cs-fixer fix -v --diff --dry-run;

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - name: Install dependencies
        run: composer update --prefer-dist
      - name: Building
        run: php -dxdebug.mode=coverage ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - php: 7.4
            dependencies: ''
          - php: 7.4
            dependencies: '--prefer-lowest --prefer-stable'
          - php: 8.0
            dependencies: ''
          - php: 8.0
            dependencies: '--prefer-lowest --prefer-stable'
          - php: 8.1
            dependencies: ''
          - php: 8.1
            dependencies: '--prefer-lowest --prefer-stable'

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Install dependencies
        run: composer update --prefer-dist ${{ matrix.dependencies }}
      - name: Building
        run: ./vendor/bin/phpunit
